# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  (1..2).each do |i|
    config.vm.define vm_name = "core-%02d" % i do |config|
		config.vm.box = "coreos"
		config.vm.box_url = "http://storage.core-os.net/coreos/amd64-generic/dev-channel/coreos_production_vagrant.box"

		config.vm.hostname = vm_name


		# i+1 because .1 address is reserved by router
		config.vm.network :private_network, ip: "192.168.65.#{i+1}"

		config.vm.synced_folder ".", "/home/core/share", id: "core-%02d" % i, :nfs => true,  :mount_options   => ['nolock,vers=3,udp']

		# Fix docker not being able to resolve private registry in VirtualBox
		config.vm.provider :virtualbox do |vb, override|
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
			vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
		end


    end
  end
end

